# Project Skyblock NeoForge metadata

modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/raziel23x/Project-Skyblock/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/project-skyblock"
logoFile="projectskyblock.png"
authors="Raziel23x"
credits="Project Skyblock community testers and contributors"
description='''
A standalone Skyblock progression and automation mod featuring resource generators,
reusable tools, reagents, configurable systems, and optional mod integrations.
Progress. Automate. Survive.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
